# Generated by Django 3.2 on 2021-04-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'managed': False},
        ),
    ]
