# Generated by Django 3.2 on 2021-04-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_mymodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mymodel',
            table='mymodel',
        ),
    ]
