# Generated by Django 3.2 on 2021-04-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_mymodel_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Jobtype',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='payid',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
        migrations.DeleteModel(
            name='Paycheck',
        ),
        migrations.DeleteModel(
            name='Timecard',
        ),
    ]
