# Generated by Django 3.2 on 2021-04-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('vacationid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('days', models.FloatField(blank=True, null=True)),
                ('approver', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacation',
                'managed': False,
            },
        ),
    ]
